GET http://api.voicerss.org/?key=bf9b0812fe864c6a8faa320ff616c7f8&b64=true&hl=en-us&src=Hello, world!
Accept: application/json

###
GET http://stoword.test/generate?word=book
Content-Type: application/json
Accept: application/json

